### ISSUE TITLE
MOTD modal reappears every time a `hi` event is received

### ISSUE THREAD

**Issue by Hri7566** [mppnet/frontend#28]
after the MOTDs were implemented, i keep receiving the "hi" message at seemingly random times

> A "hi" message is sent when the client first connects to the server. This must be sent before sending anything else (except [devices](https://github.com/mppnet/frontend/blob/main/docs/protocol.md#devices)).

> This is sent as a response when the client first sends "hi".

even your own protocol documentation implies this message shouldn't be sent multiple times on either side

**Comment by Hri7566** [comment]
this is supposedly what is happening as i haven't been able to debug it due to Murphy's law

**Comment by ar065** [comment]
Ah I know whats happening here, along with the reason of not being able to debug it (I think). It's odd, but it seems when tabbed out for long periods your client will just randomly disconnect due to what I believe is not sending the ping event in time (because of tab inactivity or whatever). I suggest you attempt to log the time in between each ping and the response (if any) the server gives before disconnecting. Other than that, nothing else should cause then since `hi` is in fact sent upon server connection. The wording in the docs is also misleading because it says "when the client first connects to the server" which implies that reconnects won't send it, which is just wrong. I'll update the docs regarding that

**Comment by lithiumjs** [comment]
The protocol is specifying that the `hi` message is only sent/received once per connection. The client is programmed in a way that if a connection is broken for any reason, it will try to reconnect to the server and send the `hi` message to establish the handshake. This has always been the case and has nothing to do with recent updates. There is a bug in the recent update however: the MOTD modal is displayed every time the client receives a `hi`, even if it's a reconnect. I'll work on fixing that, it shouldn't be hard.

**Comment by ar065** [comment]
> i experience this issue when the tab is in the foreground
Cloudflare issue iirc
